version: 2

jobs:
  deploy:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run:
          name: clone GH pages repo
          command: git clone https://${GH_TOKEN}@github.com/luminus-framework/luminus-framework.github.io.git
      - run:
          name: build site
          command: |
            lein run
            cd luminus-framework.github.io
            shopt -s extglob
            rm -rfv !("."|".."|".git")
            cp -r ../static/* .

workflows:
  version: 2
  deploy_site:
    jobs:
      - deploy

